export const SUBSTITUTIONS = {
  ING006: 'Flax egg: 1 tbsp ground flaxseed + 3 tbsp water per egg',
  ING007: 'Sour cream, skyr, or blended silken tofu',
  ING008: 'Olive oil or vegan butter',
  ING009: 'Pecorino, aged cheddar, or nutritional yeast',
  ING010: 'Coconut milk or cashew cream',
  ING013: '¼ tsp garlic powder per clove',
  ING016: 'Kale, Swiss chard, or arugula',
  ING019: 'Eggplant or extra-firm tofu',
  ING022: 'Lime, or 1 tbsp vinegar per lemon',
  ING023: '¼ tsp ground ginger per tsp fresh',
  ING025: 'Quinoa, farro, or cauliflower rice',
  ING026: 'Gluten-free pasta or zucchini noodles',
  ING027: 'Rice noodles, soba, or spaghetti squash',
  ING028: 'Gluten-free bread or lettuce wraps',
  ING029: '1:1 gluten-free flour blend',
  ING030: 'Avocado oil, canola oil, or melted butter',
  ING031: 'Tamari (gluten-free) or coconut aminos',
  ING032: 'Peanut oil plus a sprinkle of toasted sesame seeds',
  ING033: 'Maple syrup or agave nectar',
  ING034: '1 tbsp soy sauce + a pinch of sugar',
  ING035: 'Heavy cream, oat cream, or full-fat yogurt thinned with water',
  ING036: 'Cannellini beans, black beans, or lentils',
  ING037: 'Pinto or kidney beans',
  ING038: 'Tomato sauce, passata, or chopped fresh tomatoes',
  ING042: 'Cayenne pepper or your favorite hot sauce',
}
